name: Daily Commit

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "$(date)" >> activity.txt
          git config --global user.name "Aryan0854"
          git config --global user.email "YOUR_GITHUB_EMAIL"
          git add .
          git commit -m "daily commit"
          git push
